site_name: '2020-1 - Elementos de Sistemas - Z01'
theme:
  language: 'pt'
  feature:
    tabs: true
  name: 'material'
  palette:
      primary: 'white'
      accent: 'pink'
  logo:
      icon: 'developer_board'
  font:
    text: Roboto
    code: Roboto Mono
  custom_dir: 'custom_theme'

docs_dir: 'docs-src'
site_url: 'https://insper.github.io/Z01.1/'
repo_name: 'GitHub'
repo_url: 'https://github.com/insper/Z01.1'
edit_url: 'edit/docs/docs-src/'

# Copyright
copyright: 'Copyright &copy; Rafael Corsi @ insper'

nav:
- Home:
  - 'index.md'
  - 'Critérios de Avaliação': 'Sobre-Criterios-de-Avaliacao.md'
  - 'Rubricas Projetos': 'Sobre-Rubricas.md'
  - 'Util-Corona.md'

- Aulas:
  - 'Util-Aulas.md'

- 'Projetos':
#  - 'Util-Resumo-Projetos.md'
#  - 'X - Mundo real': 'X-Processadores-Projeto.md'
#  - 'J - VM Translator':
#    - 'Projeto': 'J-VMtranslator-Projeto.md'
#    - 'VM Função': 'J-VMtranslator-memoria.md'
#  - 'I - VM':
#    - 'Projeto': 'I-VM-Projeto.md'
#    - 'VM Linguagem': 'Util-Resumo-VM.md'
#    - 'VM Memória': 'I-VM-Ferramental-Memoria.md'
#  - 'H - Assembler':
#    - 'Projeto': 'H-Assembler-Projeto.md'
#    - 'Prerequisitos': 'H-Assembler-Prerequisitos.md'
#    - 'Testando': 'H-Assembler-Testando.md'
#    - 'Dicas SymbolTable': 'H-Assembler-Dicas-SymbolTable.md'
#    - 'Dicas Macro': 'H-Assembler-Dicas-Macro.md'
#  - 'G - CPU':
#    - 'CPU Projeto': 'G-CPU-Projeto.md'
#    - 'Dicas testando': 'G-CPU-Testando.md'
#    - 'Dicas rubrica B': 'G-CPU-Dicas-Conceito-B-e-A.md'
#  - 'F - Assembly':
#    - 'Projeto': 'F-Assembly-Projeto.md'
#    - 'Dicas': 'F-Assembly-Dicas.md'
#    - 'Resumo Assembly': 'Util-Resumo-Assembly.md'
#  - 'E - Lógica Sequencial': 'E-Sequencial-Projeto.md'
  - 'A-Ambiente-Desenvolvimento-Projeto.md'
  - 'LogiComb-Projeto.md'
  - 'ula-Projeto.md'
  - 'ula-Projeto-dicas.md'
  - 'seq-Projeto.md'

- Labs:
#  - 'Resumo': 'Util-Resumo-Labs.md'
#  - '17: J VM Translator Lab 1': 'J-VMtranslator-Lab-1.md'
#  - '16: I VM Lab 1': 'I-VM-Lab-1.md'
#  - '15: H Assembler Lab 1':
#      - 'H-Assembler-Lab-1.md'
#      - 'Parte 1': 'H-Assembler-Lab-1-[parte-1].md'
#      - 'Parte 2': 'H-Assembler-Lab-1-[parte-2].md'
#      - 'Parte 3': 'H-Assembler-Lab-1-[parte-3].md'
#      - 'Parte 4': 'H-Assembler-Lab-1-[parte-4].md'
#      - 'Parte 5': 'H-Assembler-Lab-1-[parte-5].md'
#  - 'Lab 14 : G CPU Lab 1': 'G-CPU-Lab-1.pdf'
#  - 'Lab 13 : F Assembly - 3': 'F-Assembly-Lab-3.md'
#  - 'Lab 12 : F Assembly - 2': 'F-Assembly-Lab-2.md'
  - 'A-Ambiente-Lab-1.md'
  - 'A-Ambiente-Lab-2.md'
  - 'A-Transistores-Lab-1.md'
  - 'LogiComb-Lab-1.md'
  - 'LogiComb-Lab-2.md'
  - 'ula-Lab-1.md'
  - 'ula-Lab-2.md'
  - 'ula-Lab-3.md'
  - 'ula-lab-4.md'
  - 'seq-Lab-1.md'
  - 'assembly-Lab-1.md'

- 'Teoria':
  - 'Teoria-Algebra-Booleana.md'
  - 'Teoria-RTL'
  - 'Teoria-Dados.md'
  - 'Teoria-Componentes.md'
  - 'Teoria-Aritmetica-Binaria.md'
  - 'Teoria-Aritmetica-Binaria-HW.md'
  - 'Teoria-ULA.md'
  - 'Teoria-Logica-Sequencial.md'
  - 'Teoria-Sequencial-Componentes.md'
  - 'Teoria-Z01.md'
  - 'Vídeo Aulas (Luciano)': 'Util-Video-Aulas.md'

- 'VHDL':
  - 'VHDL-basico.md'
  - 'VHDL-Combinacional.md'
  - 'VHDL-port-map.md'
  - 'VHDL-Sequencial.md'
  - 'VHDL-RTL.md'
  - 'VHDL-exemplos.md'

- 'Z01':
  - 'Resumo Assembly': 'Util-Resumo-Assembly.md'
  - 'Z01.1 Cheat Sheet': 'Util-Z01.1-Cheat-Sheet.md'
  - 'Instruction Set': 'Util-InstructionSet.md'
  - 'Resumo VM': 'Util-Resumo-VM.md'

- 'Estudo':
  - 'Exercicio-Algebra-Booleana-1.md'
  - 'Exercicio-Algebra-Booleana-2.md'
  - 'Exercicio-Dados-1.md'
  - 'Exercicio-Dados-2.md'
  - 'Handout Aritmetica Booleana': 'https://github.com/Insper/Z01.1/blob/master/Exercicios/Exercicio-Aritmetica-Booleana.pdf'
  - 'Lógica Sequencial - 1': 'https://forms.gle/XMsFCDMYsmz1qUP86'
- 'Avaliações':
    - 'Avaliacoes.md'

- Útil:
  - 'Util-Comecando-novo-projeto.md'
  - 'Util-vixi-sou-scrum.md'
  - 'Dicas git': 'Util-Dicas-GIT.md'
  - 'Util-Dicas-Travis.md'
  - 'Infraestrutura': 'Util-Infraestrutura.md'
  - 'Util-VM-Linux.md'

- Atendimento:
  - 'Atendimento.md'

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  - 'translate_admonitions.js'

extra_css:
  - css/printing.css

# Extensions
markdown_extensions:
  - markdown.extensions.attr_list
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
    - search
#    - pdf-export
